"""init

Revision ID: e8036563d28e
Revises: 
Create Date: 2025-08-20 19:43:48.283315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8036563d28e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eaip_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('reason_for_change', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FUTURE', 'ARCHIVED', 'HIDDEN', name='eaipstatus'), nullable=False),
    sa.Column('folder', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eaip_issue'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('password_hash', sa.String(length=63), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('name', name=op.f('uq_user_name'))
    )
    op.create_table('auth_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_auth_session_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_session'))
    )
    op.create_index(op.f('ix_auth_session_token'), 'auth_session', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_session_token'), table_name='auth_session')
    op.drop_table('auth_session')
    op.drop_table('user')
    op.drop_table('eaip_issue')
    # ### end Alembic commands ###
